### ISSUE TITLE
Keep Getting Error Regarding a Module

### ISSUE THREAD

**Issue by erfind** [gismo141/homebridge-server#10]
module.js:474
    throw err;
    ^

Error: Cannot find module '/usr/local/Cellar/node/7.1.0/bin/node/config.json'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at new Server (/usr/local/lib/node_modules/homebridge-server/index.js:17:22)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:294:32)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:80:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3

**Comment by gismo141** [comment]
Seems the same issue as in #9.

Please check if you have used the `-U` and the path to your config in your startup call.
I'll make the error handling, considering this problem, easier in the next version.
