### ISSUE TITLE
error starting Homebridge-Server

### ISSUE THREAD

**Issue by Slip7000** [gismo141/homebridge-server#16]
Hi 

I'm trying to start my Homebridge-Server on my Mac and are getting an error: 

 MQTT:.homebridge MQTT$ homebridge -D -U /Users/MQTT/.homebridge 
[12/22/2016, 10:10:56 AM] Loaded plugin: homebridge-server
[12/22/2016, 10:10:56 AM] Registering platform 'homebridge-server.Server'
[12/22/2016, 10:10:56 AM] ---
[12/22/2016, 10:10:56 AM] Loaded config.json with 1 accessories and 1 platforms.
[12/22/2016, 10:10:56 AM] ---
[12/22/2016, 10:10:56 AM] Loading 1 platforms...
[12/22/2016, 10:10:56 AM] [Homebridge Server] Initializing Server platform...
[12/22/2016, 10:10:56 AM] Loading 1 accessories...
/usr/local/lib/node_modules/homebridge/lib/api.js:46
  if (name.indexOf('.') == -1) {
          ^

TypeError: Cannot read property 'indexOf' of undefined
    at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:46:11)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:254:42)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:81:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Also my config.json file is in the .homebridge folder.

This is what my config.json consist of:

{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:4D:E3:DE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    
    "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",

    "accessories": [
        {
           
        }
    ],

    "platforms": [
        {
		"platform": "Server",
		"port": 8765,
		"name": "Homebridge Server",
		"log" : "/Users/MQTT/Documents/MQTT LOGS"
        }
    ]
}

Please assist

**Comment by gismo141** [comment]
Hi @Slip7000!

The problem you have is about the curly brackets in the accessories-section. They define a new accessory but homebridge itself fails, because there are no further information.

So in fact the problem should be solved by removing these curly brackets so that your config.json should look like:

```JSON
{
"bridge": {
"name": "Homebridge",
"username": "CC:22:4D:E3:DE:30",
"port": 51826,
"pin": "031-45-154"
},

"description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",

"accessories": [],

"platforms": [
    {
	"platform": "Server",
	"port": 8765,
	"name": "Homebridge Server",
	"log" : "/Users/MQTT/Documents/MQTT LOGS"
    }
]
}
```

Hope this solves the problem! ;)

**Comment by gismo141** [comment]
https://github.com/nfarina/homebridge/issues/1001
