### ISSUE TITLE
home bridge got error after install home bridge-server plugin

### ISSUE THREAD

**Issue by Juniorchen2012** [gismo141/homebridge-server#17]
/usr/local/lib/node_modules/homebridge/lib/server.js:176
    throw err;
    ^

SyntaxError: Unexpected token [
    at Object.parse (native)
    at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:170:19)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:44:23)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)

this is the error. thx

**Comment by gismo141** [comment]
This issue seems to be raised by Homebridge itself - could you please post your `config.json` and the plugins you`ve installed?

Thanks

**Comment by Juniorchen2012** [comment]
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "728-15-728"
    },{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "728-15-728"
    },
[{
    "platform": "Server",
    "port"    : 8765,
    "name"    : "Homebridge Server",
    "log"     : "~/log/home",
    "restart" : "ls"
}]

**Comment by Juniorchen2012** [comment]
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "728-15-728"
    },{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "728-15-728"
    },
[{
    "platform": "Server",
    "port"    : 8765,
    "name"    : "Homebridge Server",
    "log"     : "~/log/home",
    "restart" : "ls"
}]

**Comment by Juniorchen2012** [comment]
I have fixed the problem, thx
