### ISSUE TITLE
1.0.22 Update - New error at launch

### ISSUE THREAD

**Issue by chrisl10** [gismo141/homebridge-server#20]
Recently update to 1.0.22 with no changes to my config.json file. Now I get the following error when launching. Everything worked fine before update but now I get;

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8765
    at Object.exports._errnoException (util.js:1036:11)
    at exports._exceptionWithHostPort (util.js:1059:20)
    at Server._listen2 (net.js:1252:14)
    at listen (net.js:1288:10)
    at Server.listen (net.js:1384:5)
    at new ServerPlatform (/usr/local/lib/node_modules/homebridge-server/index.js:499:12)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:294:32)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:80:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by gismo141** [comment]
It seems that the port is blocked - do you maybe have another instance running?

1. stop your services. This depends on the system you're using.
2. check if any other process is using the port:

```
sudo netstat -p -a
```

3. kill all possible instances:

```
 sudo kill $(ps aux | grep '[h]omebridge' | awk '{print $2}')
```
