### ISSUE TITLE
Crash when clicking /listInstallablePlugins

### ISSUE THREAD

**Issue by hirbod** [gismo141/homebridge-server#22]
As soon as I click on plugins, the server crashes.

```log
homebridge.service - Node.js HomeKit Server
   Loaded: loaded (/etc/systemd/system/homebridge.service; enabled)
   Active: activating (auto-restart) (Result: exit-code) since Do 2017-01-12 05:35:21 CET; 2s ago
  Process: 13665 ExecStart=/usr/bin/homebridge $HOMEBRIDGE_OPTS (code=exited, status=1/FAILURE)
 Main PID: 13665 (code=exited, status=1/FAILURE)

Jan 12 05:35:21 magicmirror homebridge[13665]: at _combinedTickCallback (internal/process/next_tick.js:74:11)
Jan 12 05:35:21 magicmirror homebridge[13665]: at process._tickCallback (internal/process/next_tick.js:98:9)
Jan 12 05:35:21 magicmirror systemd[1]: homebridge.service: main process exited, code=exited, status=1/FAILURE
Jan 12 05:35:21 magicmirror systemd[1]: Unit homebridge.service entered failed state.
```

Then auto-restart from homebridge.service kicks in and reboots. 

Config:

```json
{ 
    "port": 8765,
    "log": "systemd",
    "restart": "systemctl restart homebridge.service"
}
```

**Comment by gismo141** [comment]
Could you please provide the log-file of that time with:

```
journalctl --no-pager -u homebridge --since yesterday
```

But I think this problem was related as well to #23 and #25.

**Comment by hirbod** [comment]
It was related to it. My user  "homebridge" wasn't inside the sudoers.
