### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by gielk** [gismo141/homebridge-server#38]
config file

```
{
	"bridge": {
		"name": "Homebridge",
		"username": "18:00:27:40:BC:1B",
		"port": 51925,
		"pin": "031-45-164"
	},
	"platforms": [{
		"platform": "Server",
		"port": 8765,
		"name": "HomebridgeServer",
		"log": "/Users/Admin/.homebridge/controller/logs/loging.log",
		"restart": "launchctl unload ~/Library/LaunchAgents/com.homebridge.server.plist && launchctl load ~/Library/LaunchAgents/com.homebridge.server.plist"
	}]


}
```
Error i'm getting 
````
[2017-02-22 15:31:49] [HomebridgeServer] is listening on: http://192.168.2.3:8765
[2017-02-22 15:31:49] [HomebridgeServer] is listening on: http://192.168.2.67:8765
[2017-02-22 15:31:49] Homebridge is running on port 51925.
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: bind EADDRINUSE 0.0.0.0:1982
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at dgram.js:213:18
    at doNTCallback3 (node.js:452:9)
    at process._tickCallback (node.js:358:17)
    at Function.Module.runMain (module.js:469:11)
    at startup (node.js:136:18)
    at node.js:963:3
````

what can i do ?

**Comment by gielk** [comment]
Homebridge was already running in background

**Comment by gismo141** [comment]
Sorry that I haven't answered earlier but apparently you already found the culprit ;)
