### ISSUE TITLE
can get it to work right

### ISSUE THREAD

**Issue by treeceh86** [gismo141/homebridge-server#43]
I am not sure what I am doing wrong.   this is the only plug in I can get to work correctly.

```Bash
[Homebridge Server] is listening on: http://**.**.**.**:1234
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::9876
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1259:14)
    at listen (net.js:1295:10)
    at Server.listen (net.js:1391:5)
    at new InfoPlatform (/usr/local/lib/node_modules/homebridge-info/index.js:63:12)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:294:32)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:80:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
```

**Comment by treeceh86** [comment]
port is 8765

**Comment by gismo141** [comment]
It seems like there is already an instance running. Could you please post your `config.json` as well?
As well it is strange, that it prints that it is listening on port `1234`.

**Comment by gismo141** [comment]
Closing this due to low activity
