### ISSUE TITLE
try the 'Log' page then throw this 

### ISSUE THREAD

**Issue by skyblue** [gismo141/homebridge-server#49]
homebridge-0.4.22 & node@8

-----

[2017-7-23 17:11:46] Homebridge is running on port 51826.
`/usr/local/lib/node_modules/homebridge-server/index.js:487
                          return log(err);
                                 ^

TypeError: log is not a function
    at ReadFileContext.callback (/usr/local/lib/node_modules/homebridge-server/index.js:487:34)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)

**Comment by d-lamers** [comment]
Same here

**Comment by gismo141** [comment]
Please create the log-file first if it doesn't exist and verify, that the file-path is correct.

**Comment by gismo141** [comment]
Closing due to inactivity.
