### ISSUE TITLE
Cannot read property

### ISSUE THREAD

**Issue by Kimovitzh** [gismo141/homebridge-server#57]
Hi.

When I run the homebridge after installing, I get this.

`/usr/lib/node_modules/homebridge/lib/api.js:50
  if (name.indexOf('.') == -1) {
           ^

TypeError: Cannot read property 'indexOf' of undefined
    at API.accessory (/usr/lib/node_modules/homebridge/lib/api.js:50:12)
    at Server._loadAccessories (/usr/lib/node_modules/homebridge/lib/server.js:264:42)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:86:38)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)`

Do I need to nano in to the api.js and do something or?

**Comment by gismo141** [comment]
This problem should not be related to my plugin due to the path were the error occurs.

I suspect its a typo or a duplicate in your `config.js`

**Comment by gismo141** [comment]
Closing due to inactivity
